name: Bug Report
description: Report all kinds of crashes and bugs here
title: "[Bug|Crash]: "
labels: ["bug", "crash"]
assignees:
  - octocat
body:
  - type: checkboxes
    id: checkbox1
    attributes:
      label: Have you checked if a similar issue is already reported by someone else?
      description: Please check if this issue is duplicated with the previous one. It will really help to organize the current issues for the developers.
      options:
        - label: I checked there are no similar issues have been reported.
          required: true
  - type: checkboxes
    id: checkbox2
    attributes:
      label: Have you read the support policy?
      description: "https://github.com/Yesssssman/epicfightmod/issues/1166\nPlease take a look at it before you submit any report. the violation of the policy will result in the removal of the report without any notification."
      options:
        - label: I read it and I accept the policy.
          required: true
  - type: checkboxes
    id: checkbox3
    attributes:
      label: Is this issue related to mod incompatibility?
      description: Please note that most issues regarding mod incompatibility are barely fixed because the mod code is hard to access than the vanilla Minecraft code.
      options:
        - label: This is a mod compatibility issue and I''m aware of the problem.
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
