name: Bug Report
description: Report all type of issues here
title: "[Bug|Crash]: "
labels: []
assignees:
  - octocat
body:
  - type: checkboxes
    id: checkbox1
    attributes:
      label: "Please check if a similar issue has already been reported."
      description: "You can search previously reported issues here or in our Community: https://discord.com/channels/955784714264932362/1248998577640833167"
      options:
        - label: "I checked this type of issue has never been reported."
          required: true
  - type: checkboxes
    id: checkbox2
    attributes:
      label: "Please check you're using proper versions."
      description: "Check you're using proper Minecraft, Modloader, Epic Fight, and its add-on versions. We do not support outdated versions."
      options:
        - label: "I checked they're all in the right version."
          required: true
  - type: checkboxes
    id: checkbox3
    attributes:
      label: "Please check if this issue's from out of our area"
      description: "Basically, we support issues from Epic Fight first. Please check if you have a ton of mods in your mod list or use another API rather than Forge like Optifine or Bukkit. And please consider that the issue could not be fixed forever if it's true."
      options:
        - label: "I checked the problem. "
          required: true
  - type: input
    id: specify-mod
    attributes:
      label: The name of the mod
      description: "If the issue's from another mod, Please specify the name of it. This is so important because you can save our time inspecting all mods in your crash report."
      placeholder: Mod name or URL where we can download the mod.
    validations:
      required: false
  - type: checkboxes
    id: checkbox4
    attributes:
      label: "After all of these, please check if you're just pressing the ok buttons to skip this process."
      description: "Sending a shoddy issue report greatly discourages the members of development team. Please consider again if you truly followed the checklist. We won't reply to your issue report if it's insufficient of information to fix the issue."
      options:
        - label: "I read the checklist and I promise I'll provide all the information that is needed to fix the issue"
          required: true
  - type: dropdown
    id: mc-version
    attributes:
      label: Minecraft Version
      description: "These are the versions we're supporting now"
      options:
        - 1.20.1
    validations:
      required: true
  - type: textarea
    id: the issue
    attributes:
      label: The Issue
      description: "Please tell us what went wrong in as much detail as possible."
    validations:
      required: true
  - type: textarea
    id: step-to-reproduce
    attributes:
      label: Step to Reproduce?
      description: "Please tell us how we can reproduce the issue. You can post videos, images, or lines of steps to get the same result."
    validations:
      required: true
