blank_issues_enabled: true
contact_links:
  - name: Epic Fight Discord
    url: https://discord.com/invite/NbAJwj8RHg
    about: "Get support from the community & learn about frequently asked questions !"
